### ISSUE TITLE
Unable to add my yubikey - modhex analysis fails

### ISSUE THREAD

**Issue by susannemoog** [derhansen/mfa_yubikey#5]
Hey, 

I have a yubikey that is working fine in general (on other sites) but not with this extension.

It contains characters, that the modHex preg_match in this extension does not seem to like. Here's a screenshot from the yubico demo web site with pertinent parts:
![image](https://user-images.githubusercontent.com/321804/112634948-7e69a700-8e3b-11eb-9773-1ef00356dd80.png)

It's a Yubikey 5 NFC if that's relevant.

**Comment by susannemoog** [comment]
... and I just learned why: the keyboard layout used, maybe something for the docs: https://www.yubico.com/blog/yubikey-keyboard-layouts/ << don't know how they manage to make it work on their online validator, but anyway, the solution locally is to switch the layout when adding.

**Comment by derhansen** [comment]
Really interesting. Does the validation of the OTP work for the MFA login or do you also need to change keyboard layout for the OTP validation?

**Comment by susannemoog** [comment]
For the validation, it works with my default (dvorak) layout. Only when first registering the key I need to change the layout. (Which is totally fine as it's only once).

**Comment by derhansen** [comment]
OK, thanks for the feedback. I'll check if the regex can be more general, so it is possible to register a new YubiKey when dvorak keyboard layout is used.
